language: node_js

node_js:
  - "0.10"

before_install:
  # Decrypt the private key
  - mkdir ~/.ssh
  - openssl aes-256-cbc -K $encrypted_15b7554ef6b7_key -iv $encrypted_15b7554ef6b7_iv -in bwg.enc -out ~\/.ssh/bwg -d
  # Set the permission of the key
  - chmod 600 ~/.ssh/bwg
  # Start SSH agent
  - eval $(ssh-agent)
  # Add the private key to the system
  - ssh-add ~/.ssh/bwg
  # Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config
  # Set Git config
  - git config --global user.name "Wang@Travis"
  - git config --global user.email ppdg@foxmail.com
  # Install Hexo
  - npm install hexo-cli -g
  # Clone the repository
  - git clone git@bitbucket.org:ppdg123/ghblog_source.git ghblog
  - cd ./ghblog/source/_posts/
  - git pull -f
script:
  - cd ~/ghblog
  - hexo generate
  - hexo deploy

branches:
  only:
    - master
