language: node_js
node_js:
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_15b7554ef6b7_key -iv $encrypted_15b7554ef6b7_iv
  -in bwg.enc -out ~\/.ssh/bwg -d
- chmod 600 ~/.ssh/bwg
- eval $(ssh-agent)
- ssh-add ~/.ssh/bwg
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Wang@Travis"
- git config --global user.email ppdg@foxmail.com
- npm install hexo-cli -g
- git clone git@bitbucket.org:ppdg123/ghblog_source.git ghblog
- cd ./ghblog/source/
- git clone git@github.com:ppdg123/ghblog_md.git _posts
script:
- cd ~/ghblog
- hexo generate
- hexo deploy
branches:
  only:
  - master
